### ISSUE TITLE
Stuck on welcome screen

### ISSUE THREAD

**Issue by cho2** [flathub/id.sideka.App#1]
Sideka stuck on welcome screen, no login page?

![virtualbox_endless_10_05_2018_20_44_50](https://user-images.githubusercontent.com/6271071/39872725-18c46d20-5493-11e8-886d-653f67a19619.png)

```
cho2@endless:~$ flatpak run id.sideka.App
yarn run v1.3.2
warning package.json: "dependencies" has dependency "shapefile" with range "^0.6.5" that collides with a dependency in "devDependencies" of the same name with version "^0.6.6"
$ electron ./dist
Gtk-Message: Failed to load module "atk-bridge"
Gtk-Message: Failed to load module "canberra-gtk-module"
[20:44:26.321] [info] Checking for update
[20:44:26.344] [info] checking-for-update
[20:44:40.605] [error] Error: Error: Cannot find latest-linux.yml in the latest release artifacts (https://github.com/ghk/sideka_app_server/releases/download/v2.2.0/latest-linux.yml): HttpError: 404 Not Found
"method: undefined url: https://github.com/ghk/sideka_app_server/releases/download/v2.2.0/latest-linux.yml\n\nPlease double check that your authentication token is correct. Due to security reasons actual status maybe not reported, but 404.\n"
Headers: {
  "cache-control": [
    "no-cache"
  ],
  "content-encoding": [
    "gzip"
  ],
  "content-security-policy": [
    "default-src 'none'; base-uri 'self'; connect-src 'self'; form-action 'self'; img-src data:; script-src 'self'; style-src 'unsafe-inline'"
  ],
  "content-type": [
    "text/html; charset=utf-8"
  ],
  "date": [
    "Thu, 10 May 2018 13:44:40 GMT"
  ],
  "expect-ct": [
    "max-age=2592000, report-uri=\"https://api.github.com/_private/browser/errors\""
  ],
  "server": [
    "GitHub.com"
  ],
  "set-cookie": [
    "logged_in=no; domain=.github.com; path=/; expires=Mon, 10 May 2038 13:44:40 -0000; secure; HttpOnly",
    "_gh_sess=QXZXN2g5K1QyNHJIeTZ3alFyRThkN1FBN0svckVuaThmRGVkUkVmRFRpUlR5ZUVlNi9Zc2dWWDFjdTVCNThwTEN3anlabjdEdWUwWEZ4bS82TzBVZkNDUGRrU1BuQkxvWkFrdXVGYlhWYWRUNzRPdjVuZ3lOaTNYOStTbm9weEpuL1JZKzJwanIza3R1dUt3blVGb1IwL0c0STdwL3FZUEhQYlNMaFNsRWhFd1pwRncva2tPbU5PL2Y0b1VwQkwxRmdZZjRnaFdjb3NZcDZWZERLMUQrZz09LS1xL2xzTnNJd1dMNmZjaUdNS1JKci93PT0%3D--bcc6d892c94875a274292857f3bfb5e41cc9fb0a; path=/; secure; HttpOnly"
  ],
  "status": [
    "404 Not Found"
  ],
  "strict-transport-security": [
    "max-age=31536000; includeSubdomains; preload"
  ],
  "transfer-encoding": [
    "chunked"
  ],
  "vary": [
    "X-PJAX"
  ],
  "x-content-type-options": [
    "nosniff"
  ],
  "x-frame-options": [
    "deny"
  ],
  "x-github-request-id": [
    "E030:70A0:2DCB2C:42558D:5AF44CC8"
  ],
  "x-request-id": [
    "17c27d20-de89-4432-88ed-e447fa0040f7"
  ],
  "x-runtime": [
    "0.107040"
  ],
  "x-runtime-rack": [
    "0.120562"
  ],
  "x-xss-protection": [
    "1; mode=block"
  ]
}
    at createHttpError (/app/main/node_modules/builder-util-runtime/src/httpExecutor.ts:31:10)
    at ElectronHttpExecutor.handleResponse (/app/main/node_modules/builder-util-runtime/src/httpExecutor.ts:122:7)
    at ClientRequest.request.doRequest.response (/app/main/node_modules/builder-util-runtime/src/httpExecutor.ts:84:16)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:191:7)
    at URLRequest.ClientRequest.urlRequest.on (/app/main/node_modules/electron/dist/resources/electron.asar/browser/api/net.js:207:12)
    at emitOne (events.js:96:13)
    at URLRequest.emit (events.js:191:7)
From previous event:
    at CancellationToken.createPromise (/app/main/node_modules/builder-util-runtime/src/CancellationToken.ts:51:5)
    at ElectronHttpExecutor.doApiRequest (/app/main/node_modules/builder-util-runtime/src/httpExecutor.ts:81:30)
    at ElectronHttpExecutor.request (/app/main/node_modules/builder-util-runtime/src/httpExecutor.ts:73:17)
    at /app/main/node_modules/electron-updater/src/GitHubProvider.ts:74:38
From previous event:
    at GitHubProvider.getLatestVersion (/app/main/node_modules/electron-updater/out/GitHubProvider.js:167:7)
    at /app/main/node_modules/electron-updater/src/AppUpdater.ts:293:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at AppImageUpdater.getUpdateInfo (/app/main/node_modules/electron-updater/out/AppUpdater.js:449:7)
    at /app/main/node_modules/electron-updater/src/AppUpdater.ts:297:35
    at Generator.next (<anonymous>)
From previous event:
    at AppImageUpdater.doCheckForUpdates (/app/main/node_modules/electron-updater/out/AppUpdater.js:491:7)
    at /app/main/node_modules/electron-updater/src/AppUpdater.ts:268:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at AppImageUpdater._checkForUpdates (/app/main/node_modules/electron-updater/out/AppUpdater.js:422:7)
    at AppImageUpdater.checkForUpdates (/app/main/node_modules/electron-updater/src/AppUpdater.ts:217:35)
    at WebContents.<anonymous> (/app/main/dist/index.js:1:3672)
    at Object.onceWrapper (events.js:293:19)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:194:7)
    at createHttpError (/app/main/node_modules/builder-util-runtime/src/httpExecutor.ts:31:10)
    at ElectronHttpExecutor.handleResponse (/app/main/node_modules/builder-util-runtime/src/httpExecutor.ts:122:7)
    at ClientRequest.request.doRequest.response (/app/main/node_modules/builder-util-runtime/src/httpExecutor.ts:84:16)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:191:7)
    at URLRequest.ClientRequest.urlRequest.on (/app/main/node_modules/electron/dist/resources/electron.asar/browser/api/net.js:207:12)
    at emitOne (events.js:96:13)
    at URLRequest.emit (events.js:191:7)
    at CancellationToken.createPromise (/app/main/node_modules/builder-util-runtime/src/CancellationToken.ts:51:5)
    at ElectronHttpExecutor.doApiRequest (/app/main/node_modules/builder-util-runtime/src/httpExecutor.ts:81:30)
    at ElectronHttpExecutor.request (/app/main/node_modules/builder-util-runtime/src/httpExecutor.ts:73:17)
    at /app/main/node_modules/electron-updater/src/GitHubProvider.ts:74:38
    at GitHubProvider.getLatestVersion (/app/main/node_modules/electron-updater/out/GitHubProvider.js:167:7)
    at /app/main/node_modules/electron-updater/src/AppUpdater.ts:293:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
    at AppImageUpdater.getUpdateInfo (/app/main/node_modules/electron-updater/out/AppUpdater.js:449:7)
    at /app/main/node_modules/electron-updater/src/AppUpdater.ts:297:35
    at Generator.next (<anonymous>)
    at AppImageUpdater.doCheckForUpdates (/app/main/node_modules/electron-updater/out/AppUpdater.js:491:7)
    at /app/main/node_modules/electron-updater/src/AppUpdater.ts:268:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
    at AppImageUpdater._checkForUpdates (/app/main/node_modules/electron-updater/out/AppUpdater.js:422:7)
    at AppImageUpdater.checkForUpdates (/app/main/node_modules/electron-updater/src/AppUpdater.ts:217:35)
    at WebContents.<anonymous> (/app/main/dist/index.js:1:3672)
    at Object.onceWrapper (events.js:293:19)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:194:7)
    at newError (/app/main/node_modules/builder-util-runtime/src/index.ts:23:17)
    at /app/main/node_modules/electron-updater/src/GitHubProvider.ts:78:15
    at Generator.throw (<anonymous>)
From previous event:
    at GitHubProvider.getLatestVersion (/app/main/node_modules/electron-updater/out/GitHubProvider.js:167:7)
    at /app/main/node_modules/electron-updater/src/AppUpdater.ts:293:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at AppImageUpdater.getUpdateInfo (/app/main/node_modules/electron-updater/out/AppUpdater.js:449:7)
    at /app/main/node_modules/electron-updater/src/AppUpdater.ts:297:35
    at Generator.next (<anonymous>)
From previous event:
    at AppImageUpdater.doCheckForUpdates (/app/main/node_modules/electron-updater/out/AppUpdater.js:491:7)
    at /app/main/node_modules/electron-updater/src/AppUpdater.ts:268:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at AppImageUpdater._checkForUpdates (/app/main/node_modules/electron-updater/out/AppUpdater.js:422:7)
    at AppImageUpdater.checkForUpdates (/app/main/node_modules/electron-updater/src/AppUpdater.ts:217:35)
    at WebContents.<anonymous> (/app/main/dist/index.js:1:3672)
    at Object.onceWrapper (events.js:293:19)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:194:7)
[20:44:40.633] [error] Error: Cannot find latest-linux.yml in the latest release artifacts (https://github.com/ghk/sideka_app_server/releases/download/v2.2.0/latest-linux.yml): HttpError: 404 Not Found
"method: undefined url: https://github.com/ghk/sideka_app_server/releases/download/v2.2.0/latest-linux.yml\n\nPlease double check that your authentication token is correct. Due to security reasons actual status maybe not reported, but 404.\n"
Headers: {
  "cache-control": [
    "no-cache"
  ],
  "content-encoding": [
    "gzip"
  ],
  "content-security-policy": [
    "default-src 'none'; base-uri 'self'; connect-src 'self'; form-action 'self'; img-src data:; script-src 'self'; style-src 'unsafe-inline'"
  ],
  "content-type": [
    "text/html; charset=utf-8"
  ],
  "date": [
    "Thu, 10 May 2018 13:44:40 GMT"
  ],
  "expect-ct": [
    "max-age=2592000, report-uri=\"https://api.github.com/_private/browser/errors\""
  ],
  "server": [
    "GitHub.com"
  ],
  "set-cookie": [
    "logged_in=no; domain=.github.com; path=/; expires=Mon, 10 May 2038 13:44:40 -0000; secure; HttpOnly",
    "_gh_sess=QXZXN2g5K1QyNHJIeTZ3alFyRThkN1FBN0svckVuaThmRGVkUkVmRFRpUlR5ZUVlNi9Zc2dWWDFjdTVCNThwTEN3anlabjdEdWUwWEZ4bS82TzBVZkNDUGRrU1BuQkxvWkFrdXVGYlhWYWRUNzRPdjVuZ3lOaTNYOStTbm9weEpuL1JZKzJwanIza3R1dUt3blVGb1IwL0c0STdwL3FZUEhQYlNMaFNsRWhFd1pwRncva2tPbU5PL2Y0b1VwQkwxRmdZZjRnaFdjb3NZcDZWZERLMUQrZz09LS1xL2xzTnNJd1dMNmZjaUdNS1JKci93PT0%3D--bcc6d892c94875a274292857f3bfb5e41cc9fb0a; path=/; secure; HttpOnly"
  ],
  "status": [
    "404 Not Found"
  ],
  "strict-transport-security": [
    "max-age=31536000; includeSubdomains; preload"
  ],
  "transfer-encoding": [
    "chunked"
  ],
  "vary": [
    "X-PJAX"
  ],
  "x-content-type-options": [
    "nosniff"
  ],
  "x-frame-options": [
    "deny"
  ],
  "x-github-request-id": [
    "E030:70A0:2DCB2C:42558D:5AF44CC8"
  ],
  "x-request-id": [
    "17c27d20-de89-4432-88ed-e447fa0040f7"
  ],
  "x-runtime": [
    "0.107040"
  ],
  "x-runtime-rack": [
    "0.120562"
  ],
  "x-xss-protection": [
    "1; mode=block"
  ]
}
    at createHttpError (/app/main/node_modules/builder-util-runtime/src/httpExecutor.ts:31:10)
    at ElectronHttpExecutor.handleResponse (/app/main/node_modules/builder-util-runtime/src/httpExecutor.ts:122:7)
    at ClientRequest.request.doRequest.response (/app/main/node_modules/builder-util-runtime/src/httpExecutor.ts:84:16)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:191:7)
    at URLRequest.ClientRequest.urlRequest.on (/app/main/node_modules/electron/dist/resources/electron.asar/browser/api/net.js:207:12)
    at emitOne (events.js:96:13)
    at URLRequest.emit (events.js:191:7)
From previous event:
    at CancellationToken.createPromise (/app/main/node_modules/builder-util-runtime/src/CancellationToken.ts:51:5)
    at ElectronHttpExecutor.doApiRequest (/app/main/node_modules/builder-util-runtime/src/httpExecutor.ts:81:30)
    at ElectronHttpExecutor.request (/app/main/node_modules/builder-util-runtime/src/httpExecutor.ts:73:17)
    at /app/main/node_modules/electron-updater/src/GitHubProvider.ts:74:38
From previous event:
    at GitHubProvider.getLatestVersion (/app/main/node_modules/electron-updater/out/GitHubProvider.js:167:7)
    at /app/main/node_modules/electron-updater/src/AppUpdater.ts:293:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at AppImageUpdater.getUpdateInfo (/app/main/node_modules/electron-updater/out/AppUpdater.js:449:7)
    at /app/main/node_modules/electron-updater/src/AppUpdater.ts:297:35
    at Generator.next (<anonymous>)
From previous event:
    at AppImageUpdater.doCheckForUpdates (/app/main/node_modules/electron-updater/out/AppUpdater.js:491:7)
    at /app/main/node_modules/electron-updater/src/AppUpdater.ts:268:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at AppImageUpdater._checkForUpdates (/app/main/node_modules/electron-updater/out/AppUpdater.js:422:7)
    at AppImageUpdater.checkForUpdates (/app/main/node_modules/electron-updater/src/AppUpdater.ts:217:35)
    at WebContents.<anonymous> (/app/main/dist/index.js:1:3672)
    at Object.onceWrapper (events.js:293:19)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:194:7)
    at createHttpError (/app/main/node_modules/builder-util-runtime/src/httpExecutor.ts:31:10)
    at ElectronHttpExecutor.handleResponse (/app/main/node_modules/builder-util-runtime/src/httpExecutor.ts:122:7)
    at ClientRequest.request.doRequest.response (/app/main/node_modules/builder-util-runtime/src/httpExecutor.ts:84:16)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:191:7)
    at URLRequest.ClientRequest.urlRequest.on (/app/main/node_modules/electron/dist/resources/electron.asar/browser/api/net.js:207:12)
    at emitOne (events.js:96:13)
    at URLRequest.emit (events.js:191:7)
    at CancellationToken.createPromise (/app/main/node_modules/builder-util-runtime/src/CancellationToken.ts:51:5)
    at ElectronHttpExecutor.doApiRequest (/app/main/node_modules/builder-util-runtime/src/httpExecutor.ts:81:30)
    at ElectronHttpExecutor.request (/app/main/node_modules/builder-util-runtime/src/httpExecutor.ts:73:17)
    at /app/main/node_modules/electron-updater/src/GitHubProvider.ts:74:38
    at GitHubProvider.getLatestVersion (/app/main/node_modules/electron-updater/out/GitHubProvider.js:167:7)
    at /app/main/node_modules/electron-updater/src/AppUpdater.ts:293:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
    at AppImageUpdater.getUpdateInfo (/app/main/node_modules/electron-updater/out/AppUpdater.js:449:7)
    at /app/main/node_modules/electron-updater/src/AppUpdater.ts:297:35
    at Generator.next (<anonymous>)
    at AppImageUpdater.doCheckForUpdates (/app/main/node_modules/electron-updater/out/AppUpdater.js:491:7)
    at /app/main/node_modules/electron-updater/src/AppUpdater.ts:268:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
    at AppImageUpdater._checkForUpdates (/app/main/node_modules/electron-updater/out/AppUpdater.js:422:7)
    at AppImageUpdater.checkForUpdates (/app/main/node_modules/electron-updater/src/AppUpdater.ts:217:35)
    at WebContents.<anonymous> (/app/main/dist/index.js:1:3672)
    at Object.onceWrapper (events.js:293:19)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:194:7)
    at newError (/app/main/node_modules/builder-util-runtime/src/index.ts:23:17)
    at /app/main/node_modules/electron-updater/src/GitHubProvider.ts:78:15
    at Generator.throw (<anonymous>)
From previous event:
    at GitHubProvider.getLatestVersion (/app/main/node_modules/electron-updater/out/GitHubProvider.js:167:7)
    at /app/main/node_modules/electron-updater/src/AppUpdater.ts:293:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at AppImageUpdater.getUpdateInfo (/app/main/node_modules/electron-updater/out/AppUpdater.js:449:7)
    at /app/main/node_modules/electron-updater/src/AppUpdater.ts:297:35
    at Generator.next (<anonymous>)
From previous event:
    at AppImageUpdater.doCheckForUpdates (/app/main/node_modules/electron-updater/out/AppUpdater.js:491:7)
    at /app/main/node_modules/electron-updater/src/AppUpdater.ts:268:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at AppImageUpdater._checkForUpdates (/app/main/node_modules/electron-updater/out/AppUpdater.js:422:7)
    at AppImageUpdater.checkForUpdates (/app/main/node_modules/electron-updater/src/AppUpdater.ts:217:35)
    at WebContents.<anonymous> (/app/main/dist/index.js:1:3672)
    at Object.onceWrapper (events.js:293:19)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:194:7)
```
I think should be like this
![cuplikan layar dari 2018-05-10 20-52-46](https://user-images.githubusercontent.com/6271071/39873092-2c8c41b0-5494-11e8-9de0-acbc68e1e200.png)

**Comment by uajain** [comment]
How did you install the last screenshot? Did you built this from source? 

I am taking a look at the problem.

**Comment by cho2** [comment]
> How did you install the last screenshot? Did you built this from source?

https://github.com/ghk/sideka-electron/releases/download/v2.2.10/Sideka-2.2.10-x86_64.AppImage

**Comment by uajain** [comment]
@cho2 Can you test with flathub/ Endless app center now? It should be fixed.

**Comment by cho2** [comment]
> @cho2 Can you test with flathub/ Endless app center now? It should be fixed by now.

:+1: 
![virtualbox_endless_18_05_2018_10_19_08](https://user-images.githubusercontent.com/6271071/40214443-f36a7b4e-5a84-11e8-85d5-20a062dfbebe.png)
